SYMBOLS = [
    "BTCUSDT", "ETHUSDT", "XRPUSDT", "SOLUSDT", "DOGEUSDT", "ADAUSDT", "LINKUSDT", "XLMUSDT", "AVAXUSDT", "HBARUSDT", "SHIBUSDT", "PEPEUSDT"
]

INTERVAL = "15m"                     # 1m, 5m, 15m, 1h, 4h, 1d, 1w, 1M

START_DATE = "2017-01-01"
